// <auto-generated />
using FoodCalculator.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodCalculator.Migrations
{
    [DbContext(typeof(FoodCalculatorDbContext))]
    [Migration("20240328180930_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FoodCalculator.DTOs.DayDTO", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakFast_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dinner_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lunch_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("FoodCalculator.DTOs.DayTemplatesDTO", b =>
                {
                    b.Property<int>("DayNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breakfast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dinner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DayNumber");

                    b.ToTable("DayTemplates");
                });

            modelBuilder.Entity("FoodCalculator.DTOs.FoodDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Modifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Portions")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FoodList");
                });

            modelBuilder.Entity("FoodCalculator.DTOs.FoodTypeDTO", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FoodTypes");
                });

            modelBuilder.Entity("FoodCalculator.DTOs.MealFillingDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day_Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodListOrder")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MF_Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MealFillings");
                });
#pragma warning restore 612, 618
        }
    }
}
